[tools]
cilium-cli = "latest"
helm = "latest"
kubectl = "latest"
opentofu = "latest"
talosctl = "latest"
terragrunt = "latest"
yq = "latest"

[env]
MISE_LOCAL_CONFIG_FILE = "{{ config_root }}/.config/mise/config.local.toml"
ENV_DIR = "{{ config_root }}/env"
B2_TF_BUCKET_ENDPOINT = "s3.us-west-001.backblazeb2.com"
B2_TF_BUCKET_NAME = "jleight-terraform"
